#Write a program to generate a Fibonacci series of numbers. Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series. Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....    a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.    b) Generate the series until the element in the series is less than Max number.

num=int(input("Enter number:"))
a = 0
b = 1
count=0
if num < 0:
    print("Incorrect input")
elif num == 1:
    print("\nFibonacci series:",num)
else:
   print("\nFibonacci series of",num,"numbers is :")
   while count < num:
      print(a,end=',')
      next = a + b
      a = b
      b = next
      count += 1
print()
      
